[2024-11-01T13:48:53.581+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:48:53.591+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:48:53.592+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:48:53.603+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:48:54.342+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:48:54.353+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:48:55.034+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:48:55.045+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:48:55.046+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:48:55.059+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:48:56.706+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:48:56.717+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:48:56.948+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:48:56.958+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:48:57.562+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:48:57.571+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:48:58.218+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:48:58.233+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:48:58.696+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:48:58.707+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:48:58.948+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:48:58.984+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:48:59.836+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:48:59.848+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:49:00.585+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:49:00.599+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:49:01.149+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:49:01.173+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:49:01.391+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:49:01.400+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:49:02.056+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:49:02.067+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:49:02.068+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:49:02.079+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T13:49:03.326+0000] {taskinstance.py:1969} INFO - Dependencies not met for <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2024-11-01T13:49:03.347+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2024-11-01T14:03:37.972+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [queued]>
[2024-11-01T14:03:37.981+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [queued]>
[2024-11-01T14:03:37.982+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-11-01T14:03:38.005+0000] {taskinstance.py:2217} INFO - Executing <Task(_PythonDecoratedOperator): get_data> on 2024-11-01 13:38:43.294293+00:00
[2024-11-01T14:03:38.011+0000] {standard_task_runner.py:60} INFO - Started process 878 to run task
[2024-11-01T14:03:38.014+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'updating_stock_data', 'get_data', 'manual__2024-11-01T13:38:43.294293+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/polars_postgres.py', '--cfg-path', '/tmp/tmp9fegwm6w']
[2024-11-01T14:03:38.016+0000] {standard_task_runner.py:88} INFO - Job 164: Subtask get_data
[2024-11-01T14:03:38.070+0000] {task_command.py:423} INFO - Running <TaskInstance: updating_stock_data.get_data manual__2024-11-01T13:38:43.294293+00:00 [running]> on host 07e6c451f8a5
[2024-11-01T14:03:38.148+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow_development' AIRFLOW_CTX_DAG_ID='updating_stock_data' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T13:38:43.294293+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-01T13:38:43.294293+00:00'
[2024-11-01T14:03:38.151+0000] {logging_mixin.py:188} INFO - Error: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
[2024-11-01T14:03:38.152+0000] {python.py:202} INFO - Done. Returned value was: {}
[2024-11-01T14:03:38.174+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=updating_stock_data, task_id=get_data, execution_date=20241101T133843, start_date=20241101T140337, end_date=20241101T140338
[2024-11-01T14:03:38.227+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-01T14:03:38.262+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
